### PR TITLE
Added comms.org for direct messaging

### PR DESCRIPTION
**Pull request by Anti-Distinctlyminty**

### CODE REVIEW

**Review by ihdavids — APPROVED** [review]
sounds good lets chat in there

**Comment by Anti-Distinctlyminty** [comment]
As you mentioned we wont get notified though. Maybe it's not a great idea :/
is communication via issues for _everything_ the way people collaborate?

**Comment by ihdavids** [comment]
I like the idea of documenting some of our more important discussions where others can find them. That said, I like getting notifications that you have written.
Issues work, they are intended for feature or bug discussions, but for general chatter they feel like we are abusing them a bit. I dont have a problem either way.

We could make a discord or slack channel if you would prefer.

**Comment by Anti-Distinctlyminty** [comment]
Discord will be fine. My username is Antidistinctlyminty#7580

**Pull request merged**
